### PR TITLE
add volumeExpansion, comment out kubedb for harbor

### PR DESCRIPTION
**Pull request by bit-herder**
im adding the stuff for the resize, and removing the kubedb for harbor to ensure it doesn't do weird stuff while im messing around with it.

### CODE REVIEW

**Review by grossvogel — APPROVED** [review]
I'm curious... are the PV and PVC going to hang around after commenting out the postgres or will they be deleted? (and if the latter do we ever get the data back?)

**Comment by bit-herder** [comment]
it should not do anything since garbage collection isn't enabled. If it were, I believe it would try to delete it, which would turn it into a dormant database, which im going to do anyway (but id rather control the timing heh)

**Comment by bit-herder** [comment]
> I'm curious... are the PV and PVC going to hang around after commenting out the postgres or will they be deleted? (and if the latter do we ever get the data back?)

sorry I forgot to mention that it depends on the setting of the dormantdatabase. if its set to anything other than `wipeOut` it leaves its secrets (Creds), PVCs, and snapshots. 

So what I will do here is this:

```
- [ ] add the proper StorageClass attributes to `Nightingale` to enable resize of PVC and remove the `md-harbor` kubedb definition temporarily from nightingale so I can fiddle with it without it trying to re-create or create and another DB while im touching its parts, ensuring garbage collection is off (edit: it is indeed off - we are not collecting garbage)
- [ ] manually resize pvc by editing it. 
- [ ] delete the postgres CRD for md-harbor, turning it into a DormantDatabase
- [ ] delete the DormantDatabase, which leaves the PVC, secrets, and the snapshots 
- [ ] edit the DB definition in the nightingale cluster to reflect the change in volume size, comment out the init script bits (we don't want the DB to re-init)
- [ ] push that DB definition to nightingale, causing it to "un-pause" the DB with a 10GB db now
```

**Comment by grossvogel** [comment]
@bit-herder thank you for taking the time to explain all of that!

**Comment by bit-herder** [comment]
> @bit-herder thank you for taking the time to explain all of that!

hopefully soon this won't be so weird. RN the any part of the spec.storage in the CRD is not able to be changed

**Pull request merged**
